name: Deploy Blazor App to Azure

on:
  push:
    paths:
      - 'src/**'
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x' # Adjust to your Blazor app's .NET version

    - name: Restore dependencies
      run: dotnet restore
      working-directory: src

    - name: Build the application
      run: dotnet publish -c Release -o ../publish_output
      working-directory: src

    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Deploy to Azure Web App
      run: |
        az webapp deploy --resource-group rg-cc-3-29-25 \
                         --name blazor-app-service \
                         --src-path publish_output
