name: Deploy Terraform to Azure

on:
  push:
    paths:
      - 'infra/**'
  workflow_dispatch:

permissions:
      id-token: write
      contents: read
jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Initialize Terraform
      run: terraform init -backend-config="storage_account_name=satfstateccdemodmd" -backend-config="container_name=tfstatecontainer" -backend-config="key=demetfstate" -backend-config="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}"
      working-directory: infra

    - name: Plan Terraform
      env:
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      run: terraform plan -out=tfplan
      working-directory: infra

    - name: Apply Terraform
      env:
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      run: terraform apply -auto-approve tfplan
      working-directory: infra
